### ISSUE TITLE
issue when I train on synthetic dataset

### ISSUE THREAD

**Issue by Thebluebluesky** [pengzhou1108/RGB-N#4]
Hi!
I got a problem when I run the order "./train_faster_rcnn.sh 0 coco res101_fusion EXP_DIR coco_flip_0001_bilinear_new"  
`
Traceback (most recent call last):
  File "./tools/trainval_net.py", line 111, in <module>
    imdb, roidb = combined_roidb(args.imdb_name)
  File "./tools/trainval_net.py", line 82, in combined_roidb
    roidbs = [get_roidb(s) for s in imdb_names.split('+')]
  File "./tools/trainval_net.py", line 82, in <listcomp>
    roidbs = [get_roidb(s) for s in imdb_names.split('+')]
  File "./tools/trainval_net.py", line 75, in get_roidb
    imdb = get_imdb(imdb_name)
  File "./RGB-N/tools/../lib/datasets/factory.py", line 77, in get_imdb
    return __sets[name]()
  File "./RGB-N/tools/../lib/datasets/factory.py", line 26, in <lambda>
    __sets[name] = (lambda split=split, year=year: pascal_voc(split, year))
  File "./RGB-N/tools/../lib/datasets/pascal_voc.py", line 42, in __init__
    self._image_index = self._load_image_set_index()
  File "./RGB-N/tools/../lib/datasets/pascal_voc.py", line 85, in _load_image_set_index
    'Path does not exist: {}'.format(image_set_file)
AssertionError: Path does not exist: ./RGB-N/data/VOCdevkit2007/VOC2007/ImageSets/Main/trainval.txt
`
Do you have any idea how to fix this?  THANKS

**Comment by pengzhou1108** [comment]
> Hi!
> I got a problem when I run the order "./train_faster_rcnn.sh 0 coco res101_fusion EXP_DIR coco_flip_0001_bilinear_new"
> `
> Traceback (most recent call last):
> File "./tools/trainval_net.py", line 111, in 
> imdb, roidb = combined_roidb(args.imdb_name)
> File "./tools/trainval_net.py", line 82, in combined_roidb
> roidbs = [get_roidb(s) for s in imdb_names.split('+')]
> File "./tools/trainval_net.py", line 82, in 
> roidbs = [get_roidb(s) for s in imdb_names.split('+')]
> File "./tools/trainval_net.py", line 75, in get_roidb
> imdb = get_imdb(imdb_name)
> File "./RGB-N/tools/../lib/datasets/factory.py", line 77, in get_imdb
> return __setsname
> File "./RGB-N/tools/../lib/datasets/factory.py", line 26, in 
> __sets[name] = (lambda split=split, year=year: pascal_voc(split, year))
> File "./RGB-N/tools/../lib/datasets/pascal_voc.py", line 42, in **init**
> self._image_index = self._load_image_set_index()
> File "./RGB-N/tools/../lib/datasets/pascal_voc.py", line 85, in _load_image_set_index
> 'Path does not exist: {}'.format(image_set_file)
> 
> AssertionError: Path does not exist: ./RGB-N/data/VOCdevkit2007/VOC2007/ImageSets/Main/trainval.txt
> `
> Do you have any idea how to fix this? THANKS
 Hi,

Did you change the coco path in factory.py?

**Comment by Thebluebluesky** [comment]
> > Hi!
> > I got a problem when I run the order "./train_faster_rcnn.sh 0 coco res101_fusion EXP_DIR coco_flip_0001_bilinear_new"
> > `
> > Traceback (most recent call last):
> > File "./tools/trainval_net.py", line 111, in
> > imdb, roidb = combined_roidb(args.imdb_name)
> > File "./tools/trainval_net.py", line 82, in combined_roidb
> > roidbs = [get_roidb(s) for s in imdb_names.split('+')]
> > File "./tools/trainval_net.py", line 82, in
> > roidbs = [get_roidb(s) for s in imdb_names.split('+')]
> > File "./tools/trainval_net.py", line 75, in get_roidb
> > imdb = get_imdb(imdb_name)
> > File "./RGB-N/tools/../lib/datasets/factory.py", line 77, in get_imdb
> > return __setsname
> > File "./RGB-N/tools/../lib/datasets/factory.py", line 26, in
> > __sets[name] = (lambda split=split, year=year: pascal_voc(split, year))
> > File "./RGB-N/tools/../lib/datasets/pascal_voc.py", line 42, in **init**
> > self._image_index = self._load_image_set_index()
> > File "./RGB-N/tools/../lib/datasets/pascal_voc.py", line 85, in _load_image_set_index
> > 'Path does not exist: {}'.format(image_set_file)
> > AssertionError: Path does not exist: ./RGB-N/data/VOCdevkit2007/VOC2007/ImageSets/Main/trainval.txt
> > `
> > Do you have any idea how to fix this? THANKS
> > Hi,
> 
> Did you change the coco path in factory.py?

Yes,I  did that. And I only changed the coco path in factory.py. 
Also, I found that I did not have a folder named ‘RGB-N/data’ ，I don't know where the problem is

**Comment by pengzhou1108** [comment]
> > > Hi!
> > > I got a problem when I run the order "./train_faster_rcnn.sh 0 coco res101_fusion EXP_DIR coco_flip_0001_bilinear_new"
> > > `Traceback (most recent call last): File "./tools/trainval_net.py", line 111, in imdb, roidb = combined_roidb(args.imdb_name) File "./tools/trainval_net.py", line 82, in combined_roidb roidbs = [get_roidb(s) for s in imdb_names.split('+')] File "./tools/trainval_net.py", line 82, in roidbs = [get_roidb(s) for s in imdb_names.split('+')] File "./tools/trainval_net.py", line 75, in get_roidb imdb = get_imdb(imdb_name) File "./RGB-N/tools/../lib/datasets/factory.py", line 77, in get_imdb return __setsname File "./RGB-N/tools/../lib/datasets/factory.py", line 26, in __sets[name] = (lambda split=split, year=year: pascal_voc(split, year)) File "./RGB-N/tools/../lib/datasets/pascal_voc.py", line 42, in **init** self._image_index = self._load_image_set_index() File "./RGB-N/tools/../lib/datasets/pascal_voc.py", line 85, in _load_image_set_index 'Path does not exist: {}'.format(image_set_file) AssertionError: Path does not exist: ./RGB-N/data/VOCdevkit2007/VOC2007/ImageSets/Main/trainval.txt`
> > > Do you have any idea how to fix this? THANKS
> > > Hi,
> > 
> > 
> > Did you change the coco path in factory.py?
> 
> Yes,I did that. And I only changed the coco path in factory.py.
> Also, I found that I did not have a folder named ‘RGB-N/data’ ，I don't know where the problem is

Hi,

Did you also change 'TRAIN_IMDB' in train_faster_rcnn.sh, if so keep it as 'coco_train_filter_single'? According to the error, it seems that the factory went to pascal instead of coco synthetic dataset path. The 'RGB-N/data' is where I put my ImageNet pre-trained model, however, you can download the pre-trained model and put it to your own folder.

**Comment by Thebluebluesky** [comment]
> > > > Hi!
> > > > I got a problem when I run the order "./train_faster_rcnn.sh 0 coco res101_fusion EXP_DIR coco_flip_0001_bilinear_new"
> > > > `Traceback (most recent call last): File "./tools/trainval_net.py", line 111, in imdb, roidb = combined_roidb(args.imdb_name) File "./tools/trainval_net.py", line 82, in combined_roidb roidbs = [get_roidb(s) for s in imdb_names.split('+')] File "./tools/trainval_net.py", line 82, in roidbs = [get_roidb(s) for s in imdb_names.split('+')] File "./tools/trainval_net.py", line 75, in get_roidb imdb = get_imdb(imdb_name) File "./RGB-N/tools/../lib/datasets/factory.py", line 77, in get_imdb return __setsname File "./RGB-N/tools/../lib/datasets/factory.py", line 26, in __sets[name] = (lambda split=split, year=year: pascal_voc(split, year)) File "./RGB-N/tools/../lib/datasets/pascal_voc.py", line 42, in **init** self._image_index = self._load_image_set_index() File "./RGB-N/tools/../lib/datasets/pascal_voc.py", line 85, in _load_image_set_index 'Path does not exist: {}'.format(image_set_file) AssertionError: Path does not exist: ./RGB-N/data/VOCdevkit2007/VOC2007/ImageSets/Main/trainval.txt`
> > > > Do you have any idea how to fix this? THANKS
> > > > Hi,
> > > 
> > > 
> > > Did you change the coco path in factory.py?
> > 
> > 
> > Yes,I did that. And I only changed the coco path in factory.py.
> > Also, I found that I did not have a folder named ‘RGB-N/data’ ，I don't know where the problem is
> 
> Hi,
> 
> Did you also change 'TRAIN_IMDB' in train_faster_rcnn.sh, if so keep it as 'coco_train_filter_single'? According to the error, it seems that the factory went to pascal instead of coco synthetic dataset path. The 'RGB-N/data' is where I put my ImageNet pre-trained model, however, you can download the pre-trained model and put it to your own folder.

I didn't change 'TRAIN_IMDB',but I did do something different in train_faster_rcnn.sh
when I download faster_rcnn, I did not found a '.ckpt' document ,instead I got four files name as 
'
res101_faster_rcnn_iter_110000.ckpt.data-00000-of-00001  
res101_faster_rcnn_iter_110000.ckpt.meta
res101_faster_rcnn_iter_110000.ckpt.index               
 res101_faster_rcnn_iter_110000.pkl
'
I did know if it's the right thing to do ,but I change the weight in  train_faster_rcnn.sh to '.pkl' cause I did not have a '.ckpt' file

**Comment by wangvenn** [comment]
> > > > > Hi!
> > > > > I got a problem when I run the order "./train_faster_rcnn.sh 0 coco res101_fusion EXP_DIR coco_flip_0001_bilinear_new"
> > > > > `Traceback (most recent call last): File "./tools/trainval_net.py", line 111, in imdb, roidb = combined_roidb(args.imdb_name) File "./tools/trainval_net.py", line 82, in combined_roidb roidbs = [get_roidb(s) for s in imdb_names.split('+')] File "./tools/trainval_net.py", line 82, in roidbs = [get_roidb(s) for s in imdb_names.split('+')] File "./tools/trainval_net.py", line 75, in get_roidb imdb = get_imdb(imdb_name) File "./RGB-N/tools/../lib/datasets/factory.py", line 77, in get_imdb return __setsname File "./RGB-N/tools/../lib/datasets/factory.py", line 26, in __sets[name] = (lambda split=split, year=year: pascal_voc(split, year)) File "./RGB-N/tools/../lib/datasets/pascal_voc.py", line 42, in **init** self._image_index = self._load_image_set_index() File "./RGB-N/tools/../lib/datasets/pascal_voc.py", line 85, in _load_image_set_index 'Path does not exist: {}'.format(image_set_file) AssertionError: Path does not exist: ./RGB-N/data/VOCdevkit2007/VOC2007/ImageSets/Main/trainval.txt`
> > > > > Do you have any idea how to fix this? THANKS
> > > > > Hi,
> > > > 
> > > > 
> > > > Did you change the coco path in factory.py?
> > > 
> > > 
> > > Yes,I did that. And I only changed the coco path in factory.py.
> > > Also, I found that I did not have a folder named ‘RGB-N/data’ ，I don't know where the problem is
> > 
> > 
> > Hi,
> > Did you also change 'TRAIN_IMDB' in train_faster_rcnn.sh, if so keep it as 'coco_train_filter_single'? According to the error, it seems that the factory went to pascal instead of coco synthetic dataset path. The 'RGB-N/data' is where I put my ImageNet pre-trained model, however, you can download the pre-trained model and put it to your own folder.
> 
> I didn't change 'TRAIN_IMDB',but I did do something different in train_faster_rcnn.sh
> when I download faster_rcnn, I did not found a '.ckpt' document ,instead I got four files name as
> '
> res101_faster_rcnn_iter_110000.ckpt.data-00000-of-00001
> res101_faster_rcnn_iter_110000.ckpt.meta
> res101_faster_rcnn_iter_110000.ckpt.index
> res101_faster_rcnn_iter_110000.pkl
> '
> I did know if it's the right thing to do ,but I change the weight in train_faster_rcnn.sh to '.pkl' cause I did not have a '.ckpt' file

Hi, you'd better down this ckpt "wget -v http://download.tensorflow.org/models/resnet_v1_101_2016_08_28.tar.gz" from (https://github.com/endernewton/tf-faster-rcnn)
